cors:
  originPatterns: https://localhost:8080,http://localhost:5173
server:
  port: 8080

# Spring
spring:
  application:
    name: "Voz Cidada API"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/voz-cidada
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# SpringDoc (Swagger UI) Configuration
springdoc:
  swagger-ui:
    url: /openapi.yml

# Logging Configuration
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF

# Security Token Configuration
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expire-length: 3600

# AWS S3 Configuration
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}